import { getSupabaseClient } from "@/lib/supabase/client";
import type { Campaign, CampaignDraft, CampaignChannel, CampaignStatus } from "./types";
export type CampaignRow = { id:string; name:string; description:string|null; goal:string|null; status:CampaignStatus; owner:string|null; channel:CampaignChannel|null; start_date:string|null; end_date:string|null; budget:number|string; spend:number|string; target_leads:number; created_at:string; updated_at:string; };
const columns="id,name,description,goal,status,owner,channel,start_date,end_date,budget,spend,target_leads,created_at,updated_at";
export function mapCampaignRow(row:CampaignRow,actualLeads=0):Campaign { return { id:row.id,name:row.name,description:row.description??"",goal:row.goal??"",status:row.status,owner:row.owner??"",channel:row.channel??"Offline",startDate:row.start_date??"",endDate:row.end_date??"",budget:Number(row.budget),spend:Number(row.spend),targetLeads:row.target_leads,actualLeads,createdAt:row.created_at,updatedAt:row.updated_at }; }
export function toCampaignRow(d:CampaignDraft){return {name:d.name,description:d.description||null,goal:d.goal||null,status:d.status,owner:d.owner||null,channel:d.channel,start_date:d.startDate||null,end_date:d.endDate||null,budget:d.budget,spend:d.spend??0,target_leads:d.targetLeads};}
export async function fetchCampaigns(){const client=getSupabaseClient();const[campaignsResult,leadsResult]=await Promise.all([client.from("campaigns").select(columns).order("created_at",{ascending:false}),client.from("leads").select("campaign_id")]);if(campaignsResult.error)throw campaignsResult.error;if(leadsResult.error)throw leadsResult.error;const counts=new Map<string,number>();for(const row of leadsResult.data??[]){if(row.campaign_id)counts.set(row.campaign_id,(counts.get(row.campaign_id)??0)+1);}return(campaignsResult.data as CampaignRow[]).map((row)=>mapCampaignRow(row,counts.get(row.id)??0));}
export async function fetchCampaign(id:string){const{data,error}=await getSupabaseClient().from("campaigns").select(columns).eq("id",id).single();if(error)throw error;return mapCampaignRow(data as CampaignRow);}
export async function createCampaign(d:CampaignDraft){const{data,error}=await getSupabaseClient().from("campaigns").insert(toCampaignRow(d)).select(columns).single();if(error)throw error;return mapCampaignRow(data as CampaignRow);}
export async function updateCampaign(id:string,d:CampaignDraft){const{data,error}=await getSupabaseClient().from("campaigns").update(toCampaignRow(d)).eq("id",id).select(columns).single();if(error)throw error;return mapCampaignRow(data as CampaignRow);}
export async function deleteCampaign(id:string){const{error}=await getSupabaseClient().from("campaigns").delete().eq("id",id);if(error)throw error;}
