import{getSupabaseClient}from"@/lib/supabase/client";import type{Task,TaskDraft,TaskPriority,TaskStatus,TaskType}from"./types";
export type TaskRow={id:string;title:string;description:string|null;type:TaskType;status:TaskStatus;priority:TaskPriority;owner:string|null;due_at:string|null;lead_id:string|null;opportunity_id:string|null;campaign_id:string|null;activity_id:string|null;created_at:string;updated_at:string;completed_at:string|null};
const columns="id,title,description,type,status,priority,owner,due_at,lead_id,opportunity_id,campaign_id,activity_id,created_at,updated_at,completed_at";
export function mapTaskRow(r:TaskRow):Task{return{id:r.id,title:r.title,description:r.description??"",type:r.type,status:r.status,priority:r.priority,owner:r.owner??"",dueAt:r.due_at??"",leadId:r.lead_id??"",opportunityId:r.opportunity_id??"",campaignId:r.campaign_id??"",activityId:r.activity_id??"",createdAt:r.created_at,updatedAt:r.updated_at,completedAt:r.completed_at??""};}
export function toTaskRow(d:TaskDraft){return{title:d.title,description:d.description||null,type:d.type,status:d.status,priority:d.priority,owner:d.owner||null,due_at:normalizeTimestamp(d.dueAt),lead_id:d.leadId||null,opportunity_id:d.opportunityId||null,campaign_id:d.campaignId||null,activity_id:d.activityId||null,completed_at:normalizeTimestamp(d.completedAt)};}
function normalizeTimestamp(value?:string){if(!value)return null;const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:parsed.toISOString();}
export async function fetchTasks(){const{data,error}=await getSupabaseClient().from("tasks").select(columns).order("updated_at",{ascending:false});if(error)throw error;return(data as TaskRow[]).map(mapTaskRow);}
export async function createTask(d:TaskDraft){const{data,error}=await getSupabaseClient().from("tasks").insert(toTaskRow(d)).select(columns).single();if(error)throw error;return mapTaskRow(data as TaskRow);}
export async function updateTask(id:string,d:TaskDraft){const{data,error}=await getSupabaseClient().from("tasks").update(toTaskRow(d)).eq("id",id).select(columns).single();if(error)throw error;return mapTaskRow(data as TaskRow);}
export async function deleteTask(id:string){const{error}=await getSupabaseClient().from("tasks").delete().eq("id",id);if(error)throw error;}
