import type { Campaign } from "@/components/campaigns/types";
import type { LeadRecord } from "@/components/leads/types";
import { OpportunityStatusBadge } from "./status-badge";
import type { Opportunity } from "./types";

const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric" });
export function OpportunityDetailModal({ opportunity, leads, campaigns, onClose, onEdit }: { opportunity: Opportunity; leads: LeadRecord[]; campaigns: Campaign[]; onClose: () => void; onEdit: () => void }) {
  const lead = leads.find((item) => String(item.id) === opportunity.leadId);
  const campaign = campaigns.find((item) => String(item.id) === opportunity.campaignId);
  const rows = [["Company", opportunity.company || "—"], ["Campaign", campaign?.name || "—"], ["Lead", lead?.name || "—"], ["Owner", opportunity.owner || "—"], ["Expected Close", opportunity.expectedCloseDate ? date.format(new Date(`${opportunity.expectedCloseDate}T00:00:00Z`)) : "—"], ["Created", date.format(new Date(opportunity.createdAt))], ["Updated", date.format(new Date(opportunity.updatedAt))]];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="w-full max-w-xl rounded-2xl bg-[#fdfcf9] shadow-2xl"><div className="flex items-start justify-between border-b border-zinc-200 p-6"><div><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-zinc-500">Opportunity</p><h2 className="mt-3 text-2xl font-semibold text-zinc-950">{opportunity.name}</h2><div className="mt-3"><OpportunityStatusBadge stage={opportunity.stage} /></div></div><button onClick={onClose} className="text-xl text-zinc-400">×</button></div><div className="p-6"><p className="metric-value text-[42px] text-zinc-950">{currency.format(opportunity.value)}</p><dl className="mt-8 grid gap-5 sm:grid-cols-2">{rows.map(([label, value]) => <div key={label}><dt className="text-[10px] uppercase tracking-[0.16em] text-zinc-500">{label}</dt><dd className="mt-2 text-sm text-zinc-800">{value}</dd></div>)}</dl>{opportunity.notes && <div className="mt-6 border-t border-zinc-200 pt-5"><p className="text-[10px] uppercase tracking-[0.16em] text-zinc-500">Notes</p><p className="mt-2 text-sm leading-6 text-zinc-700">{opportunity.notes}</p></div>}</div><div className="flex justify-end gap-3 border-t border-zinc-200 px-6 py-4"><button onClick={onClose} className="rounded-[10px] border border-zinc-200 bg-white px-4 py-2 text-sm">Close</button><button onClick={onEdit} className="rounded-[10px] bg-zinc-900 px-4 py-2 text-sm text-white">Edit</button></div></div></div>;
}
