import type { Campaign } from "@/components/campaigns/types";
import type { LeadRecord } from "@/components/leads/types";
import { OpportunityStatusBadge } from "./status-badge";
import type { Opportunity } from "./types";

const currency = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const date = new Intl.DateTimeFormat("en-US", { year: "numeric", month: "short", day: "numeric", timeZone: "UTC" });
const formatDate = (value: string) => value ? date.format(new Date(`${value.slice(0, 10)}T00:00:00Z`)) : "—";

type Props = { opportunities: Opportunity[]; leads: LeadRecord[]; campaigns: Campaign[]; onView: (item: Opportunity) => void; onEdit: (item: Opportunity) => void; onDelete: (item: Opportunity) => void };
export function OpportunityTable({ opportunities, leads, campaigns, onView, onEdit, onDelete }: Props) {
  const leadNames = new Map(leads.map((item) => [String(item.id), item.name]));
  const campaignNames = new Map(campaigns.map((item) => [String(item.id), item.name]));
  if (!opportunities.length) return <div className="rounded-[14px] border border-dashed border-zinc-300 bg-white px-6 py-16 text-center"><p className="font-medium text-zinc-950">No opportunities yet.</p><p className="mt-2 text-sm text-zinc-500">Create one from a qualified lead or add an opportunity manually.</p></div>;
  return <div className="overflow-hidden rounded-[14px] border border-zinc-200/80 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1320px] text-left text-sm"><thead className="bg-zinc-50 text-[10px] uppercase tracking-[0.16em] text-zinc-500"><tr><th className="px-5 py-4">Opportunity</th><th className="px-4 py-4">Company</th><th className="px-4 py-4">Campaign</th><th className="px-4 py-4">Lead</th><th className="px-4 py-4">Stage</th><th className="px-4 py-4">Value</th><th className="px-4 py-4">Owner</th><th className="px-4 py-4">Expected Close</th><th className="px-4 py-4">Updated</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-zinc-100">{opportunities.map((item) => <tr key={item.id} className="hover:bg-zinc-50/60"><td className="px-5 py-5"><button onClick={() => onView(item)} className="font-medium text-zinc-950 hover:text-violet-700">{item.name}</button></td><td className="px-4 py-5 text-zinc-600">{item.company || "—"}</td><td className="px-4 py-5 text-zinc-600">{campaignNames.get(item.campaignId) || "—"}</td><td className="px-4 py-5 text-zinc-600">{leadNames.get(item.leadId) || "—"}</td><td className="px-4 py-5"><OpportunityStatusBadge stage={item.stage} /></td><td className="px-4 py-5 font-semibold tabular-nums text-zinc-900">{currency.format(item.value)}</td><td className="px-4 py-5 text-zinc-600">{item.owner || "—"}</td><td className="px-4 py-5 whitespace-nowrap text-zinc-700">{formatDate(item.expectedCloseDate)}</td><td className="px-4 py-5 whitespace-nowrap text-zinc-500">{formatDate(item.updatedAt)}</td><td className="px-5 py-5"><div className="flex justify-end gap-2"><button onClick={() => onEdit(item)} className="rounded-lg border border-zinc-200 px-2.5 py-1.5 text-xs text-zinc-600 hover:bg-zinc-50">Edit</button><button onClick={() => onDelete(item)} className="rounded-lg px-2.5 py-1.5 text-xs text-rose-500 hover:bg-rose-50">Delete</button></div></td></tr>)}</tbody></table></div></div>;
}
