import{getSupabaseClient}from"@/lib/supabase/client";import type{Opportunity,OpportunityDraft,OpportunityStage}from"./types";
export type OpportunityRow={id:string;lead_id:string|null;campaign_id:string|null;name:string;company:string|null;stage:OpportunityStage;value:number|string;owner:string|null;expected_close_date:string|null;notes:string|null;created_at:string;updated_at:string};
const columns="id,lead_id,campaign_id,name,company,stage,value,owner,expected_close_date,notes,created_at,updated_at";
export function mapOpportunityRow(r:OpportunityRow):Opportunity{return{id:r.id,leadId:r.lead_id??"",campaignId:r.campaign_id??"",name:r.name,company:r.company??"",stage:r.stage,value:Number(r.value),owner:r.owner??"",expectedCloseDate:r.expected_close_date??"",notes:r.notes??"",createdAt:r.created_at,updatedAt:r.updated_at};}
export function toOpportunityRow(d:OpportunityDraft){return{lead_id:d.leadId||null,campaign_id:d.campaignId||null,name:d.name,company:d.company||null,stage:d.stage,value:d.value,owner:d.owner||null,expected_close_date:d.expectedCloseDate||null,notes:d.notes||null};}
export async function fetchOpportunities(campaignId?:string){let q=getSupabaseClient().from("opportunities").select(columns).order("updated_at",{ascending:false});if(campaignId)q=q.eq("campaign_id",campaignId);const{data,error}=await q;if(error)throw error;return(data as OpportunityRow[]).map(mapOpportunityRow);}
export async function createOpportunity(d:OpportunityDraft){const{data,error}=await getSupabaseClient().from("opportunities").insert(toOpportunityRow(d)).select(columns).single();if(error)throw error;return mapOpportunityRow(data as OpportunityRow);}
export async function updateOpportunity(id:string,d:OpportunityDraft){const{data,error}=await getSupabaseClient().from("opportunities").update(toOpportunityRow(d)).eq("id",id).select(columns).single();if(error)throw error;return mapOpportunityRow(data as OpportunityRow);}
export async function deleteOpportunity(id:string){const{error}=await getSupabaseClient().from("opportunities").delete().eq("id",id);if(error)throw error;}
