import {getSupabaseClient} from "@/lib/supabase/client"; import type{Activity,ActivityDraft,ActivityStatus,ActivityType}from"./types";
export type ActivityRow={id:string;campaign_id:string|null;partner_id:string|null;name:string;type:ActivityType;status:ActivityStatus;owner:string|null;start_date:string|null;end_date:string|null;budget:number|string;spend:number|string;target_leads:number;attendees:number;location:string|null;notes:string|null;created_at:string;updated_at:string;campaigns:{name:string}|null;partners:{name:string}|null};
const columns="id,campaign_id,partner_id,name,type,status,owner,start_date,end_date,budget,spend,target_leads,attendees,location,notes,created_at,updated_at,campaigns(name),partners(name)";
export function mapActivityRow(r:ActivityRow):Activity{return{id:r.id,campaignId:r.campaign_id??"",partnerId:r.partner_id??"",name:r.name,type:r.type,status:r.status,owner:r.owner??"",startDate:r.start_date??"",endDate:r.end_date??"",budget:Number(r.budget),spend:Number(r.spend),targetLeads:r.target_leads,attendees:r.attendees,location:r.location??"",notes:r.notes??"",campaign:r.campaigns?.name??"未关联",partner:r.partners?.name??"未关联",createdAt:r.created_at,updatedAt:r.updated_at};}
export function toActivityRow(d:ActivityDraft){return{campaign_id:d.campaignId||null,partner_id:d.partnerId||null,name:d.name,type:d.type,status:d.status,owner:d.owner||null,start_date:d.startDate||null,end_date:d.endDate||null,budget:d.budget,spend:d.spend??0,target_leads:d.targetLeads??0,attendees:d.attendees,location:d.location||null,notes:d.notes||null};}
export async function fetchActivities(campaignId?:string){let q=getSupabaseClient().from("activities").select(columns).order("start_date");if(campaignId)q=q.eq("campaign_id",campaignId);const{data,error}=await q;if(error)throw error;return(data as unknown as ActivityRow[]).map(mapActivityRow);}
export async function createActivity(d:ActivityDraft){const{data,error}=await getSupabaseClient().from("activities").insert(toActivityRow(d)).select(columns).single();if(error)throw error;return mapActivityRow(data as unknown as ActivityRow);}
export async function updateActivity(id:string,d:ActivityDraft){const{data,error}=await getSupabaseClient().from("activities").update(toActivityRow(d)).eq("id",id).select(columns).single();if(error)throw error;return mapActivityRow(data as unknown as ActivityRow);}
export async function deleteActivity(id:string){const{error}=await getSupabaseClient().from("activities").delete().eq("id",id);if(error)throw error;}
