"use client";
import { useEffect,useState } from "react";
import { fetchCampaigns } from "@/components/campaigns/supabase-data";
import { fetchActivities } from "@/components/activities/supabase-data";
import { fetchLeadsFromSupabase } from "@/components/leads/supabase-data";
import { fetchOpportunities } from "@/components/opportunities/supabase-data";
import { fetchTasks } from "@/components/tasks/supabase-data";
import type { Campaign } from "@/components/campaigns/types";import type{Activity}from"@/components/activities/types";import type{LeadRecord}from"@/components/leads/types";import type{Opportunity}from"@/components/opportunities/types";import type{Task}from"@/components/tasks/types";
import { calculatePerformance } from "@/components/campaigns/performance";
import { calculateCampaignComparison,calculateDataQuality,calculateFollowUpEffectiveness,calculateFollowUpSpeed,calculateFunnelBreakdown,calculateFunnelDiagnostics,calculateOverdueFollowUps,calculateOwnerAnalysis,calculateSourceAnalysis,classifySourceQuality,comparePeriods,medianFirstContactHours,weeklyTrend } from "./analytics";

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});const percent=(v:number|null)=>v===null?"—":`${v.toFixed(1)}%`;
export function AnalyticsCenter(){
 const[campaigns,setCampaigns]=useState<Campaign[]>([]),[activities,setActivities]=useState<Activity[]>([]),[leads,setLeads]=useState<LeadRecord[]>([]),[opportunities,setOpportunities]=useState<Opportunity[]>([]),[tasks,setTasks]=useState<Task[]>([]);const[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<string[]>([]),[breakdown,setBreakdown]=useState<"Campaign"|"Source"|"Activity Type">("Source");
 useEffect(()=>{let active=true;Promise.all([fetchCampaigns(),fetchActivities(),fetchLeadsFromSupabase(),fetchOpportunities(),fetchTasks()]).then(([c,a,l,o,t])=>{if(!active)return;setCampaigns(c);setActivities(a);setLeads(l);setOpportunities(o);setTasks(t);setSelected(c.slice(0,Math.min(3,c.length)).map(item=>String(item.id)));}).catch(()=>active&&setError("Unable to load Analytics data from Supabase. No fallback metrics are shown.")).finally(()=>active&&setLoading(false));return()=>{active=false};},[]);
 const totalSpend=campaigns.reduce((sum,item)=>sum+(item.spend??0),0),overall=calculatePerformance(leads,opportunities,totalSpend,campaigns.reduce((sum,item)=>sum+item.targetLeads,0));
 const comparisons=calculateCampaignComparison(campaigns.filter(item=>selected.includes(String(item.id))),leads,opportunities);const sourceResult=calculateSourceAnalysis(leads,opportunities),quality=classifySourceQuality(sourceResult.rows),funnel=calculateFunnelDiagnostics(leads,opportunities),followup=calculateFollowUpEffectiveness(leads,opportunities),speed=calculateFollowUpSpeed(leads,opportunities),overdue=calculateOverdueFollowUps(leads),owners=calculateOwnerAnalysis(leads,opportunities,tasks),dataQuality=calculateDataQuality(campaigns,leads,opportunities,tasks),breakdowns=calculateFunnelBreakdown(leads,opportunities,activities,breakdown);
 const leadTrend=weeklyTrend(leads,item=>item.createdAt),oppTrend=weeklyTrend(opportunities,item=>item.createdAt),taskCreated=weeklyTrend(tasks,item=>item.createdAt),taskCompleted=weeklyTrend(tasks.filter(item=>item.completedAt),item=>item.completedAt);const leadChange=comparePeriods(leadTrend.at(-1)?.count??0,leadTrend.at(-2)?.count??0);
 const highlights:string[]=[];if(funnel.largestDropOff)highlights.push(`Largest funnel drop-off currently occurs at ${funnel.largestDropOff}.`);const highest=[...sourceResult.rows].filter(r=>r.qualifiedRate!==null).sort((a,b)=>(b.qualifiedRate??0)-(a.qualifiedRate??0))[0];if(highest)highlights.push(`${highest.source} currently has the highest qualified rate (${percent(highest.qualifiedRate)}) among recorded sources.`);const revenue=[...comparisons].sort((a,b)=>b.metrics.wonRevenue-a.metrics.wonRevenue)[0];if(revenue)highlights.push(`${revenue.campaign.name} currently has the highest Won Revenue among selected campaigns.`);const overdueOwner=[...owners].sort((a,b)=>b.overdueTasks-a.overdueTasks)[0];if(overdueOwner?.overdueTasks)highlights.push(`${overdueOwner.owner} currently has the highest number of overdue tasks (${overdueOwner.overdueTasks}).`);
 if(loading)return <div className="rounded-2xl border border-zinc-200 bg-white p-12 text-center text-sm text-zinc-500">Loading Analytics from Supabase...</div>;if(error)return <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-sm text-red-700">{error}</div>;
 const kpis=[["Total Spend",money.format(overall.spend)],["Leads",overall.leads],["Qualified Leads",overall.qualifiedLeads],["Leads with Opportunity",overall.leadsWithOpportunity],["Open Pipeline",money.format(overall.openPipeline)],["Won Revenue",money.format(overall.wonRevenue)],["ROI",percent(overall.roi)],["ROAS",overall.roas===null?"—":`${overall.roas.toFixed(2)}x`]];
 return <div className="space-y-10"><section><p className="section-label">Analysis Scope</p><h2 className="mt-3 text-xl font-semibold">All Campaigns</h2><div className="mt-6 grid gap-px overflow-hidden rounded-2xl border border-[#dddcd7] bg-[#dddcd7] sm:grid-cols-2 xl:grid-cols-4">{kpis.map(([l,v])=><Metric key={String(l)} label={String(l)} value={String(v)}/>)}</div></section>
 <Section title="Analytics Highlights" note="Deterministic observations from current recorded data; no AI or causal inference."><ul className="grid gap-3 md:grid-cols-2">{highlights.length?highlights.map(x=><li key={x} className="rounded-xl bg-[#f3effc] p-4 text-sm leading-6 text-zinc-700">{x}</li>):<li className="text-sm text-zinc-500">No reliable highlight is available.</li>}</ul></Section>
 <Section title="Campaign Comparison" note="Select 2–4 campaigns. Bars and values show differences, not good/bad ratings."><div className="mb-5 flex flex-wrap gap-2">{campaigns.map(c=><label key={c.id} className={`rounded-lg border px-3 py-2 text-xs ${selected.includes(String(c.id))?"border-violet-300 bg-violet-50":"border-zinc-200"}`}><input className="mr-2" type="checkbox" checked={selected.includes(String(c.id))} onChange={()=>setSelected(current=>current.includes(String(c.id))?(current.length>2?current.filter(id=>id!==String(c.id)):current):current.length<4?[...current,String(c.id)]:current)}/>{c.name}</label>)}</div><Table headers={["Campaign","Spend","Budget Used","Leads","Qualified","Qualified Rate","Leads w/ Opp","Lead → Opp","Opp Count","Open Pipeline","Won Revenue","CPL","CPQL","Win Rate","ROI","ROAS","Target"]}>{comparisons.map(({campaign,metrics,budgetUtilization,qualifiedRate})=><tr key={campaign.id}><Td strong>{campaign.name}</Td><Td>{money.format(metrics.spend)}</Td><Td>{percent(budgetUtilization)}</Td><Td>{metrics.leads}</Td><Td>{metrics.qualifiedLeads}</Td><Td>{percent(qualifiedRate)}</Td><Td>{metrics.leadsWithOpportunity}</Td><Td>{percent(metrics.leadToOpportunityRate)}</Td><Td>{metrics.opportunities}</Td><Td>{money.format(metrics.openPipeline)}</Td><Td>{money.format(metrics.wonRevenue)}</Td><Td>{metrics.cpl===null?"—":money.format(metrics.cpl)}</Td><Td>{metrics.cpql===null?"—":money.format(metrics.cpql)}</Td><Td>{percent(metrics.winRate)}</Td><Td>{percent(metrics.roi)}</Td><Td>{metrics.roas===null?"—":`${metrics.roas.toFixed(2)}x`}</Td><Td>{percent(metrics.targetLeadAttainment)}</Td></tr>)}</Table></Section>
 <Section title="Source Analysis" note={`${sourceResult.unattributedOpportunities} Opportunities cannot be attributed to a Source because they lack a valid Lead link. Source CPL/ROI is intentionally omitted.`}><Table headers={["Source","Leads","Qualified","Qualified Rate","Leads w/ Opp","Opportunity Rate","Won Leads","Won Revenue"]}>{sourceResult.rows.map(r=><tr key={r.source}><Td strong>{r.source}{r.smallSample&&<small className="block text-amber-700">Small sample — interpret with caution.</small>}</Td><Td>{r.leads}</Td><Td>{r.qualifiedLeads}</Td><Td>{percent(r.qualifiedRate)}</Td><Td>{r.leadsWithOpportunity}</Td><Td>{percent(r.opportunityRate)}</Td><Td>{r.wonLeads}</Td><Td>{money.format(r.wonRevenue)}</Td></tr>)}</Table><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{quality.map(r=><div key={r.source} className="rounded-xl border border-zinc-200 p-4"><p className="font-medium">{r.source}</p><p className="mt-2 text-xs text-zinc-500">{r.classification}</p></div>)}</div><p className="mt-3 text-xs text-zinc-500">Relative grouping uses the current dataset median, not an industry benchmark.</p></Section>
 <Section title="Funnel Diagnostics" note={funnel.largestDropOff?`Largest current drop-off: ${funnel.largestDropOff}. No cause is inferred.`:"No drop-off can be calculated."}><div className="grid gap-px overflow-hidden rounded-xl border border-zinc-200 bg-zinc-200 md:grid-cols-4">{funnel.rows.map(r=><Metric key={r.label} label={r.label} value={String(r.count)} detail={r.conversionFromPrevious===null?"Entry stage":`${percent(r.conversionFromPrevious)} conversion · ${r.dropOffCount} drop-off`}/>)}</div><div className="mt-6 flex items-center gap-3"><span className="text-xs font-medium">Breakdown</span><select value={breakdown} onChange={e=>setBreakdown(e.target.value as typeof breakdown)} className="rounded-lg border border-zinc-200 bg-white px-3 py-2 text-sm"><option>Campaign</option><option>Source</option><option>Activity Type</option></select></div><div className="mt-4 grid gap-3 lg:grid-cols-2">{breakdowns.map(row=><div key={row.segment} className="rounded-xl border border-zinc-200 p-4"><div className="flex justify-between"><strong>{row.segment}</strong>{row.smallSample&&<span className="text-xs text-amber-700">Small sample — interpret with caution.</span>}</div><p className="mt-3 text-xs text-zinc-500">{row.funnel.map(stage=>`${stage.label}: ${stage.count}`).join(" · ")}</p></div>)}</div></Section>
 <Section title="Follow-up Effectiveness" note="This is a correlation observation only. It does not prove that contact caused conversion."><div className="grid gap-4 md:grid-cols-2">{followup.map(r=><Metric key={r.label} label={r.label} value={String(r.leads)} detail={`Qualified ${percent(r.qualifiedRate)} · Lead → Opportunity ${percent(r.opportunityRate)}${r.smallSample?" · Small sample":""}`}/>)}</div><p className="mt-5 text-sm text-zinc-600">Median time to first contact: {medianFirstContactHours(leads)===null?"—":`${medianFirstContactHours(leads)?.toFixed(1)} hours`}.</p><Table headers={["Contact speed","Leads","Qualified Rate","Lead → Opportunity"]}>{speed.map(r=><tr key={r.bucket}><Td strong>{r.bucket}{r.smallSample&&<small className="block text-amber-700">Small sample</small>}</Td><Td>{r.leads}</Td><Td>{percent(r.qualifiedRate)}</Td><Td>{percent(r.opportunityRate)}</Td></tr>)}</Table><div className="mt-5 rounded-xl bg-[#f3effc] p-5"><div className="grid gap-3 sm:grid-cols-3"><p className="font-medium">Overdue: {overdue.count}</p><p className="font-medium">Due today: {overdue.dueToday}</p><p className="font-medium">No next follow-up: {overdue.noNextFollowUp}</p></div><p className="mt-2 text-sm text-zinc-600">Overdue status distribution: {overdue.byStatus.map(x=>`${x.status}: ${x.count}`).join(" · ")||"No overdue follow-ups"}</p></div></Section>
 <Section title="Owner Workload & Outcomes" note="Operational workload and recorded outcomes only; this is not an employee rating."><Table headers={["Owner","Assigned Leads","Qualified Rate","Leads w/ Opp","Open Tasks","Overdue Tasks"]}>{owners.map(r=><tr key={r.owner}><Td strong>{r.owner}</Td><Td>{r.assignedLeads}</Td><Td>{percent(r.qualifiedRate)}</Td><Td>{r.leadsWithOpportunity}</Td><Td>{r.openTasks}</Td><Td>{r.overdueTasks}</Td></tr>)}</Table></Section>
 <Section title="8-Week Activity Trends" note="Uses reliable created_at/completed_at fields. Won Revenue by week is intentionally not shown because no reliable won_at/closed_at exists."><p className="mb-5 text-sm text-zinc-600">Latest Lead period: {leadChange.current}; previous: {leadChange.previous}; change: {leadChange.absoluteChange>=0?"+":""}{leadChange.absoluteChange}; percentage: {leadChange.percentageChange===null?"—":percent(leadChange.percentageChange)}.</p><Trend title="New Leads" rows={leadTrend}/><Trend title="New Opportunities" rows={oppTrend}/><Trend title="Tasks Created" rows={taskCreated}/><Trend title="Tasks Completed" rows={taskCompleted}/></Section>
 <Section title="Data Quality" note="Completeness indicators show where missing data may limit analysis; they are not a combined score."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(dataQuality).map(([key,value])=><div key={key} className="rounded-xl border border-zinc-200 p-4"><p className="text-xs capitalize text-zinc-500">{key.replaceAll(/([A-Z])/g," $1")}</p><p className="metric-value mt-3 text-[30px]">{percent(value.coverage)}</p><p className="mt-2 text-xs text-zinc-500">{value.complete} of {value.total} complete</p></div>)}</div></Section></div>;
}
function Section({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="rounded-2xl border border-[#e2ded8] bg-[#fdfcf9] p-6 sm:p-8"><p className="section-label">Decision Analytics</p><h2 className="mt-3 text-xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{note}</p><div className="mt-6">{children}</div></section>}
function Metric({label,value,detail}:{label:string;value:string;detail?:string}){return <div className="bg-[#fdfcf9] p-5"><p className="section-label">{label}</p><p className="metric-value mt-4 text-[30px]">{value}</p>{detail&&<p className="mt-2 text-xs text-zinc-500">{detail}</p>}</div>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-zinc-200 text-[10px] uppercase tracking-[.14em] text-zinc-500"><tr>{headers.map(h=><th className="px-4 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-zinc-100">{children}</tbody></table></div>}
function Td({children,strong=false}:{children:React.ReactNode;strong?:boolean}){return <td className={`whitespace-nowrap px-4 py-4 ${strong?"font-medium text-zinc-950":"text-zinc-600"}`}>{children}</td>}
function Trend({title,rows}:{title:string;rows:{week:string;count:number}[]}){const max=Math.max(...rows.map(r=>r.count),1);return <div className="mb-5"><div className="mb-2 flex justify-between text-xs"><strong>{title}</strong><span className="text-zinc-500">{rows.reduce((s,r)=>s+r.count,0)} records</span></div>{rows.length?<><div className="flex h-24 items-end gap-2 border-b border-zinc-200">{rows.map(r=><div key={r.week} className="group relative flex-1 bg-[#a997f0]" style={{height:`${Math.max((r.count/max)*100,3)}%`}} title={`${r.week}: ${r.count}`}><span className="sr-only">{r.week}: {r.count}</span></div>)}</div><div className="mt-2 flex justify-between text-[10px] text-zinc-400"><span>{rows[0]?.week}</span><span>{rows.at(-1)?.week}</span></div></>:<p className="border-b border-zinc-200 py-8 text-center text-xs text-zinc-400">No records in the available 8-week window.</p>}</div>}
