import { getSupabaseClient } from "@/lib/supabase/client"; import type {Partner,PartnerDraft,PartnerStatus,PartnerType} from "./types";
export type PartnerRow={id:string;name:string;company:string|null;type:PartnerType;status:PartnerStatus;region:string|null;email:string|null;phone:string|null;notes:string|null;created_at:string;updated_at:string};
const columns="id,name,company,type,status,region,email,phone,notes,created_at,updated_at";
export function mapPartnerRow(r:PartnerRow,activityCount=0,leadCount=0):Partner{return{id:r.id,name:r.name,company:r.company??"",type:r.type,status:r.status,region:r.region??"",email:r.email??"",phone:r.phone??"",notes:r.notes??"",activityCount,leadCount,createdAt:r.created_at,updatedAt:r.updated_at};}
export function toPartnerRow(d:PartnerDraft){return{name:d.name,company:d.company||null,type:d.type,status:d.status,region:d.region||null,email:d.email||null,phone:d.phone||null,notes:d.notes||null};}
export async function fetchPartners(){const client=getSupabaseClient();const[partnersResult,activitiesResult,leadsResult]=await Promise.all([client.from("partners").select(columns).order("created_at",{ascending:false}),client.from("activities").select("partner_id"),client.from("leads").select("partner_id")]);if(partnersResult.error)throw partnersResult.error;if(activitiesResult.error)throw activitiesResult.error;if(leadsResult.error)throw leadsResult.error;const activityCounts=new Map<string,number>();const leadCounts=new Map<string,number>();for(const row of activitiesResult.data??[]){if(row.partner_id)activityCounts.set(row.partner_id,(activityCounts.get(row.partner_id)??0)+1);}for(const row of leadsResult.data??[]){if(row.partner_id)leadCounts.set(row.partner_id,(leadCounts.get(row.partner_id)??0)+1);}return(partnersResult.data as PartnerRow[]).map((row)=>mapPartnerRow(row,activityCounts.get(row.id)??0,leadCounts.get(row.id)??0));}
export async function createPartner(d:PartnerDraft){const{data,error}=await getSupabaseClient().from("partners").insert(toPartnerRow(d)).select(columns).single();if(error)throw error;return mapPartnerRow(data as PartnerRow);}
export async function updatePartner(id:string,d:PartnerDraft){const{data,error}=await getSupabaseClient().from("partners").update(toPartnerRow(d)).eq("id",id).select(columns).single();if(error)throw error;return mapPartnerRow(data as PartnerRow);}
export async function deletePartner(id:string){const{error}=await getSupabaseClient().from("partners").delete().eq("id",id);if(error)throw error;}
