"use client";

import { useEffect, useState } from "react";
import { exportLeadsCsv } from "./csv-export";
import { LeadFormModal } from "./lead-form-modal";
import { LeadImportModal } from "./lead-import-modal";
import { LeadTable } from "./lead-table";
import { initialLeads } from "./mock-data";
import { createLeadInSupabase, createLeadsBatchInSupabase, deleteLeadFromSupabase, fetchLeadsFromSupabase, updateLeadFollowUpInSupabase, updateLeadInSupabase, updateLeadStatusInSupabase } from "./supabase-data";
import { leadSources, leadStatuses, type LeadDraft, type LeadRecord } from "./types";
import { fetchCampaigns } from "@/components/campaigns/supabase-data";
import { fetchActivities } from "@/components/activities/supabase-data";
import { fetchPartners } from "@/components/partners/supabase-data";
import type { Campaign } from "@/components/campaigns/types";
import type { Activity } from "@/components/activities/types";
import type { Partner } from "@/components/partners/types";
import { OpportunityFormModal } from "@/components/opportunities/opportunity-form-modal";
import { leadStatusAfterOpportunityCreation } from "@/components/opportunities/logic";
import { createOpportunity, deleteOpportunity } from "@/components/opportunities/supabase-data";
import type { OpportunityDraft } from "@/components/opportunities/types";
import { fetchOpportunities } from "@/components/opportunities/supabase-data";
import type { Opportunity } from "@/components/opportunities/types";
import { LeadDetailModal } from "./lead-detail-modal";
import { markAsContactedChanges, matchesLeadQuickFilter, type LeadQuickFilter } from "./follow-up";
import { TaskFormModal } from "@/components/tasks/task-form-modal";
import { createTask } from "@/components/tasks/supabase-data";
import type { TaskDraft } from "@/components/tasks/types";

export function LeadsManager() {
  const [leads, setLeads] = useState<LeadRecord[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [operationError, setOperationError] = useState(""); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("All"); const [sourceFilter, setSourceFilter] = useState("All"); const [editingLead, setEditingLead] = useState<LeadRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [importOpen, setImportOpen] = useState(false);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [activities, setActivities] = useState<Activity[]>([]); const [partners, setPartners] = useState<Partner[]>([]);
  const [opportunityLead, setOpportunityLead] = useState<LeadRecord | null>(null); const [opportunityError, setOpportunityError] = useState("");
  const [opportunities, setOpportunities] = useState<Opportunity[]>([]); const [viewingLead, setViewingLead] = useState<LeadRecord | null>(null); const [taskLead, setTaskLead] = useState<LeadRecord | null>(null); const [taskError, setTaskError] = useState(""); const [quickFilter, setQuickFilter] = useState<LeadQuickFilter>("all");
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("followup") as LeadQuickFilter | null; let active = true; Promise.all([fetchLeadsFromSupabase(), fetchCampaigns(), fetchActivities(), fetchPartners(), fetchOpportunities()]).then(([leadItems, campaignItems, activityItems, partnerItems, opportunityItems]) => { if (active) { setLeads(leadItems); setCampaigns(campaignItems); setActivities(activityItems); setPartners(partnerItems); setOpportunities(opportunityItems); if (requested && ["all","needs","today","overdue","none"].includes(requested)) setQuickFilter(requested); } }).catch(() => { if (active) { setLoadError("无法完整读取 Supabase 关联数据，当前显示本地示例 Leads。请先执行 V3 migration。"); setLeads(initialLeads); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const term = search.trim().toLocaleLowerCase();
  const filteredLeads = leads.filter((lead) => (lead.name.toLocaleLowerCase().includes(term) || lead.company.toLocaleLowerCase().includes(term)) && (statusFilter === "All" || lead.status === statusFilter) && (sourceFilter === "All" || lead.source === sourceFilter) && matchesLeadQuickFilter(lead, quickFilter));
  function openCreateForm() { setOperationError(""); setEditingLead(null); setFormOpen(true); } function openEditForm(lead: LeadRecord) { setOperationError(""); setEditingLead(lead); setFormOpen(true); }
  async function saveLead(draft: LeadDraft) { setOperationError(""); try { if (editingLead && typeof editingLead.id === "string") { const updated = await updateLeadInSupabase(editingLead.id, draft); setLeads((current) => current.map((item) => item.id === updated.id ? updated : item)); } else if (editingLead) { setLeads((current) => current.map((item) => item.id === editingLead.id ? { ...draft, id: item.id } : item)); } else { const created = await createLeadInSupabase(draft); setLeads((current) => [created, ...current]); } setFormOpen(false); } catch { setOperationError(`无法${editingLead ? "保存修改" : "创建 Lead"}，Supabase 写入失败。请检查网络和数据库权限后重试。`); } }
  async function deleteLead(lead: LeadRecord) { if (!window.confirm(`确定删除“${lead.name}”吗？`)) return; setOperationError(""); try { if (typeof lead.id === "string") await deleteLeadFromSupabase(lead.id); setLeads((current) => current.filter((item) => item.id !== lead.id)); } catch { setOperationError("无法删除 Lead，Supabase 写入失败。数据仍然保留，请检查网络和数据库权限后重试。"); } }
  async function importLeads(drafts: LeadDraft[]) { const created = await createLeadsBatchInSupabase(drafts); setLeads((current) => [...created, ...current]); return created.length; }
  async function createOpportunityFromLead(draft: OpportunityDraft) { setOpportunityError(""); try { const created = await createOpportunity(draft); if (opportunityLead && typeof opportunityLead.id === "string") { const nextStatus = leadStatusAfterOpportunityCreation(opportunityLead.status); if (nextStatus) { try { await updateLeadStatusInSupabase(opportunityLead.id, nextStatus); } catch (syncError) { await deleteOpportunity(created.id); throw syncError; } setLeads((current) => current.map((lead) => lead.id === opportunityLead.id ? { ...lead, status: nextStatus } : lead)); } } setOpportunityLead(null); } catch { setOpportunityError("Opportunity and Lead could not be saved consistently. The new Opportunity was rolled back where possible; check Supabase permissions and retry."); } }
  async function markContacted(lead: LeadRecord) { if (typeof lead.id !== "string") return; setOperationError(""); try { const updated = await updateLeadFollowUpInSupabase(lead.id, markAsContactedChanges(lead)); setLeads((current) => current.map((item) => item.id === updated.id ? updated : item)); setViewingLead(updated); } catch { setOperationError("Lead could not be marked as contacted."); } }
  async function createFollowUpTask(draft: TaskDraft) { setTaskError(""); try { await createTask(draft); setTaskLead(null); } catch { setTaskError("Follow-up Task could not be created. Run the V3 migration and check permissions."); } }
  function clearFilters() { setSearch(""); setStatusFilter("All"); setSourceFilter("All"); setQuickFilter("all"); }
  const controlClass = "h-10 rounded-[10px] border border-zinc-200 bg-white px-3 text-[13px] text-zinc-700 outline-none transition focus:border-zinc-400 focus:ring-2 focus:ring-zinc-900/5";
  if (loading) return <div className="rounded-2xl border border-slate-200 bg-white px-6 py-14 text-center shadow-sm"><div className="mx-auto size-8 animate-spin rounded-full border-2 border-slate-200 border-t-teal-600" /><p className="mt-4 text-sm font-medium text-slate-600">正在从 Supabase 加载 Leads...</p></div>;
  return <>{loadError && <div className="mb-5 rounded-[12px] border border-amber-200/70 bg-amber-50/70 px-4 py-3 text-sm text-amber-800" role="alert">{loadError}</div>}{operationError && <div className="mb-5 rounded-[12px] border border-rose-200/70 bg-rose-50/70 px-4 py-3 text-sm text-rose-800" role="alert">{operationError}</div>}<div className="mb-4 flex flex-wrap gap-2">{([['all','All'],['needs','Needs Follow-up'],['today','Due Today'],['overdue','Overdue'],['none','No Follow-up']] as const).map(([value,label])=><button key={value} onClick={()=>setQuickFilter(value)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${quickFilter===value?'bg-[#eeeafd] text-violet-800':'border border-zinc-200 bg-white text-zinc-600'}`}>{label}</button>)}</div><section className="mb-6 flex flex-col gap-3 rounded-[14px] border border-zinc-200/80 bg-white p-3.5 shadow-sm xl:flex-row xl:items-center xl:justify-between"><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(240px,1fr)_180px_180px_auto]">
    <label className="relative"><span className="sr-only">按姓名或公司搜索</span><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${controlClass} w-full pl-10`} placeholder="搜索姓名或公司" /><span aria-hidden="true" className="absolute left-3.5 top-2.5 text-slate-400">⌕</span></label>
    <label><span className="sr-only">按状态筛选</span><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className={`${controlClass} w-full`}><option value="All">全部状态</option>{leadStatuses.map((item) => <option key={item}>{item}</option>)}</select></label>
    <label><span className="sr-only">按来源筛选</span><select value={sourceFilter} onChange={(e) => setSourceFilter(e.target.value)} className={`${controlClass} w-full`}><option value="All">全部来源</option>{leadSources.map((item) => <option key={item}>{item}</option>)}</select></label>
    {(search || statusFilter !== "All" || sourceFilter !== "All") && <button type="button" onClick={clearFilters} className="h-10 rounded-[10px] px-3 text-[13px] text-zinc-500 transition hover:bg-zinc-100">清除筛选</button>}</div><div className="flex shrink-0 flex-wrap gap-2"><button type="button" onClick={() => setImportOpen(true)} className="h-10 rounded-[10px] border border-zinc-200 bg-white px-3.5 text-[13px] font-medium text-zinc-700 transition hover:bg-zinc-50">Import CSV</button><button type="button" onClick={() => exportLeadsCsv(filteredLeads)} disabled={filteredLeads.length === 0} className="h-10 rounded-[10px] border border-zinc-200 bg-white px-3.5 text-[13px] font-medium text-zinc-700 transition hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-50">Export CSV</button><button type="button" onClick={openCreateForm} className="h-10 rounded-[10px] bg-zinc-900 px-4 text-[13px] font-medium text-white transition hover:bg-zinc-800">＋ 新建 Lead</button></div></section>
    <div className="mb-3 px-1 text-sm text-slate-500">显示 {filteredLeads.length} / {leads.length} 个 Lead</div><LeadTable leads={filteredLeads} onView={setViewingLead} onEdit={openEditForm} onDelete={deleteLead} onCreateOpportunity={(lead) => { setOpportunityError(""); setOpportunityLead(lead); }} />{formOpen && <LeadFormModal lead={editingLead} campaigns={campaigns} activities={activities} partners={partners} saveError={operationError} onClose={() => setFormOpen(false)} onSave={saveLead} />}{importOpen && <LeadImportModal existingEmails={leads.map((lead) => lead.email)} onClose={() => setImportOpen(false)} onImport={importLeads} />}{opportunityLead && <OpportunityFormModal initialLead={opportunityLead} leads={leads} campaigns={campaigns} error={opportunityError} onClose={() => setOpportunityLead(null)} onSave={createOpportunityFromLead} />}{viewingLead&&<LeadDetailModal lead={viewingLead} onClose={()=>setViewingLead(null)} onEdit={()=>{setEditingLead(viewingLead);setViewingLead(null);setFormOpen(true);}} onCreateOpportunity={()=>{setOpportunityLead(viewingLead);setViewingLead(null);}} onMarkContacted={()=>markContacted(viewingLead)} onCreateTask={()=>{setTaskLead(viewingLead);setViewingLead(null);}}/>}{taskLead&&<TaskFormModal initialLead={taskLead} leads={leads} opportunities={opportunities} campaigns={campaigns} activities={activities} error={taskError} onClose={()=>setTaskLead(null)} onSave={createFollowUpTask}/>}</>;
}
