"use client";

import { useEffect, useMemo, useState } from "react";
import { exportLeadsCsv } from "./csv-export";
import { LeadFormModal } from "./lead-form-modal";
import { LeadImportModal } from "./lead-import-modal";
import { LeadTable } from "./lead-table";
import { initialLeads } from "./mock-data";
import { createLeadInSupabase, deleteLeadFromSupabase, fetchLeadsFromSupabase, updateLeadInSupabase } from "./supabase-data";
import { leadSources, leadStatuses, type LeadDraft, type LeadRecord } from "./types";

export function LeadsManager() {
  const [leads, setLeads] = useState<LeadRecord[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [operationError, setOperationError] = useState(""); const [search, setSearch] = useState(""); const [statusFilter, setStatusFilter] = useState("All"); const [sourceFilter, setSourceFilter] = useState("All"); const [editingLead, setEditingLead] = useState<LeadRecord | null>(null); const [formOpen, setFormOpen] = useState(false); const [importOpen, setImportOpen] = useState(false);
  useEffect(() => { let active = true; fetchLeadsFromSupabase().then((items) => { if (active) setLeads(items); }).catch(() => { if (active) { setLoadError("无法从 Supabase 读取 Leads，当前显示本地示例数据。请检查连接配置后重试。"); setLeads(initialLeads); } }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filteredLeads = useMemo(() => { const term = search.trim().toLocaleLowerCase(); return leads.filter((lead) => (lead.name.toLocaleLowerCase().includes(term) || lead.company.toLocaleLowerCase().includes(term)) && (statusFilter === "All" || lead.status === statusFilter) && (sourceFilter === "All" || lead.source === sourceFilter)); }, [leads, search, sourceFilter, statusFilter]);
  function openCreateForm() { setOperationError(""); setEditingLead(null); setFormOpen(true); } function openEditForm(lead: LeadRecord) { setOperationError(""); setEditingLead(lead); setFormOpen(true); }
  async function saveLead(draft: LeadDraft) { setOperationError(""); try { if (editingLead && typeof editingLead.id === "string") { const updated = await updateLeadInSupabase(editingLead.id, draft); setLeads((current) => current.map((item) => item.id === updated.id ? updated : item)); } else if (editingLead) { setLeads((current) => current.map((item) => item.id === editingLead.id ? { ...draft, id: item.id } : item)); } else { const created = await createLeadInSupabase(draft); setLeads((current) => [created, ...current]); } setFormOpen(false); } catch { setOperationError(`无法${editingLead ? "保存修改" : "创建 Lead"}，Supabase 写入失败。请检查网络和数据库权限后重试。`); } }
  async function deleteLead(lead: LeadRecord) { if (!window.confirm(`确定删除“${lead.name}”吗？`)) return; setOperationError(""); try { if (typeof lead.id === "string") await deleteLeadFromSupabase(lead.id); setLeads((current) => current.filter((item) => item.id !== lead.id)); } catch { setOperationError("无法删除 Lead，Supabase 写入失败。数据仍然保留，请检查网络和数据库权限后重试。"); } }
  function importLeads(drafts: LeadDraft[]) { const firstId = Date.now(); setLeads((current) => [...drafts.map((draft, index) => ({ ...draft, id: firstId + index })), ...current]); setImportOpen(false); }
  function clearFilters() { setSearch(""); setStatusFilter("All"); setSourceFilter("All"); }
  const controlClass = "h-10 rounded-[10px] border border-zinc-200 bg-white px-3 text-[13px] text-zinc-700 outline-none transition focus:border-zinc-400 focus:ring-2 focus:ring-zinc-900/5";
  if (loading) return <div className="rounded-2xl border border-slate-200 bg-white px-6 py-14 text-center shadow-sm"><div className="mx-auto size-8 animate-spin rounded-full border-2 border-slate-200 border-t-teal-600" /><p className="mt-4 text-sm font-medium text-slate-600">正在从 Supabase 加载 Leads...</p></div>;
  return <>{loadError && <div className="mb-5 rounded-[12px] border border-amber-200/70 bg-amber-50/70 px-4 py-3 text-sm text-amber-800" role="alert">{loadError}</div>}{operationError && <div className="mb-5 rounded-[12px] border border-rose-200/70 bg-rose-50/70 px-4 py-3 text-sm text-rose-800" role="alert">{operationError}</div>}<section className="mb-6 flex flex-col gap-3 rounded-[14px] border border-zinc-200/80 bg-white p-3.5 shadow-sm xl:flex-row xl:items-center xl:justify-between"><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(240px,1fr)_180px_180px_auto]">
    <label className="relative"><span className="sr-only">按姓名或公司搜索</span><input value={search} onChange={(e) => setSearch(e.target.value)} className={`${controlClass} w-full pl-10`} placeholder="搜索姓名或公司" /><span aria-hidden="true" className="absolute left-3.5 top-2.5 text-slate-400">⌕</span></label>
    <label><span className="sr-only">按状态筛选</span><select value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)} className={`${controlClass} w-full`}><option value="All">全部状态</option>{leadStatuses.map((item) => <option key={item}>{item}</option>)}</select></label>
    <label><span className="sr-only">按来源筛选</span><select value={sourceFilter} onChange={(e) => setSourceFilter(e.target.value)} className={`${controlClass} w-full`}><option value="All">全部来源</option>{leadSources.map((item) => <option key={item}>{item}</option>)}</select></label>
    {(search || statusFilter !== "All" || sourceFilter !== "All") && <button type="button" onClick={clearFilters} className="h-10 rounded-[10px] px-3 text-[13px] text-zinc-500 transition hover:bg-zinc-100">清除筛选</button>}</div><div className="flex shrink-0 flex-wrap gap-2"><button type="button" onClick={() => setImportOpen(true)} className="h-10 rounded-[10px] border border-zinc-200 bg-white px-3.5 text-[13px] font-medium text-zinc-700 transition hover:bg-zinc-50">Import CSV</button><button type="button" onClick={() => exportLeadsCsv(filteredLeads)} disabled={filteredLeads.length === 0} className="h-10 rounded-[10px] border border-zinc-200 bg-white px-3.5 text-[13px] font-medium text-zinc-700 transition hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-50">Export CSV</button><button type="button" onClick={openCreateForm} className="h-10 rounded-[10px] bg-zinc-900 px-4 text-[13px] font-medium text-white transition hover:bg-zinc-800">＋ 新建 Lead</button></div></section>
    <div className="mb-3 px-1 text-sm text-slate-500">显示 {filteredLeads.length} / {leads.length} 个 Lead</div><LeadTable leads={filteredLeads} onEdit={openEditForm} onDelete={deleteLead} />{formOpen && <LeadFormModal lead={editingLead} saveError={operationError} onClose={() => setFormOpen(false)} onSave={saveLead} />}{importOpen && <LeadImportModal onClose={() => setImportOpen(false)} onImport={importLeads} />}</>;
}
