import { LeadStatusBadge } from "./status-badge";
import type { LeadRecord } from "./types";

type LeadTableProps = { leads: LeadRecord[]; onView: (lead: LeadRecord) => void; onEdit: (lead: LeadRecord) => void; onDelete: (lead: LeadRecord) => void };

export function LeadTable({ leads, onView, onEdit, onDelete }: LeadTableProps) {
  if (leads.length === 0) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center"><p className="font-medium text-slate-900">没有找到 Lead</p><p className="mt-2 text-sm text-slate-500">请尝试调整搜索关键词或筛选条件。</p></div>;
  return <div className="overflow-hidden rounded-[14px] border border-zinc-200/80 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1420px] text-left text-sm">
    <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3.5 font-semibold">Name</th><th className="px-4 py-3.5 font-semibold">Company</th><th className="px-4 py-3.5 font-semibold">Campaign</th><th className="px-4 py-3.5 font-semibold">Status</th><th className="px-4 py-3.5 font-semibold">Owner</th><th className="px-4 py-3.5 font-semibold">Next Follow-up</th><th className="px-4 py-3.5 font-semibold">Follow-up Status</th><th className="px-5 py-3.5 text-right font-semibold">操作</th></tr></thead>
    <tbody className="divide-y divide-slate-100">{leads.map((lead) => <tr key={lead.id} className="transition hover:bg-slate-50/80">
      <td className="px-5 py-5"><button onClick={()=>onView(lead)} className="font-medium text-slate-950 hover:text-violet-700">{lead.name}</button><p className="mt-1 text-xs text-slate-500">{lead.email}</p></td><td className="px-4 py-5 text-slate-600">{lead.company}</td><td className="max-w-56 px-4 py-5 text-slate-600">{lead.campaign}</td><td className="px-4 py-5"><LeadStatusBadge status={lead.status} /></td><td className="px-4 py-5 text-slate-600">{lead.owner}</td><td className="px-4 py-5 whitespace-nowrap text-slate-700">{lead.nextFollowUpAt?new Date(lead.nextFollowUpAt).toLocaleString():"—"}</td><td className="px-4 py-5 text-slate-600">{lead.followUpStatus||"—"}</td><td className="px-5 py-5"><div className="flex justify-end gap-1.5"><button type="button" onClick={() => onView(lead)} className="rounded-lg border border-violet-200 bg-violet-50/60 px-2.5 py-1.5 text-xs font-medium text-violet-700 transition hover:bg-violet-100/70">查看</button><button type="button" onClick={() => onEdit(lead)} className="rounded-lg border border-zinc-200 px-2.5 py-1.5 text-xs font-medium text-zinc-600 transition hover:bg-zinc-50 hover:text-zinc-900">编辑</button><button type="button" onClick={() => onDelete(lead)} className="rounded-lg px-2.5 py-1.5 text-xs font-medium text-rose-500 transition hover:bg-rose-50/70 hover:text-rose-700">删除</button></div></td>
    </tr>)}</tbody>
  </table></div></div>;
}
