import type { Lead } from "./types";

export const initialLeads: Lead[] = [
  { id: 1, name: "刘晨", company: "远航智能科技", email: "chen.liu@example.com", phone: "+86 138 1100 1001", source: "Webinar", campaign: "行业解决方案 Webinar", activity: "企业增长战略 Webinar", partner: "商业增长周刊", status: "Qualified", potentialValue: 280000, owner: "赵欣", createdAt: "2026-09-28" },
  { id: 2, name: "Grace Tan", company: "Vertex Systems", email: "grace@example.com", phone: "+65 6123 2010", source: "Event", campaign: "2026 Q4 品牌声量计划", activity: "品牌合作伙伴峰会", partner: "Northstar Creative", status: "Opportunity", potentialValue: 520000, owner: "林悦", createdAt: "2026-08-29" },
  { id: 3, name: "周海峰", company: "恒峰制造", email: "haifeng@example.com", phone: "+86 139 2200 3020", source: "Field Demo", campaign: "渠道伙伴增长计划", activity: "智能制造现场演示", partner: "华东渠道联盟", status: "Won", potentialValue: 760000, owner: "王明", createdAt: "2026-08-18" },
  { id: 4, name: "Emily Wong", company: "Aurora Retail", email: "emily@example.com", phone: "+852 2988 3201", source: "Campaign", campaign: "新品 Nova 发布 Campaign", activity: "Nova 产品发布会", partner: "Northstar Creative", status: "Contacted", potentialValue: 190000, owner: "陈森", createdAt: "2026-09-01" },
  { id: 5, name: "高源", company: "新域数据", email: "yuan.gao@example.com", phone: "+86 136 3000 2188", source: "Organic", campaign: "未关联", activity: "未关联", partner: "未关联", status: "New", potentialValue: 85000, owner: "周岚", createdAt: "2026-09-02" },
  { id: 6, name: "Akira Mori", company: "Sakura Industrial", email: "akira@example.com", phone: "+81 3 5511 8842", source: "Partner", campaign: "亚太市场认知提升", activity: "东京行业媒体交流会", partner: "Peak AV Solutions", status: "Qualified", potentialValue: 340000, owner: "叶宁", createdAt: "2026-08-26" },
  { id: 7, name: "孙曼", company: "蓝图软件", email: "man.sun@example.com", phone: "+86 137 4400 6712", source: "Event", campaign: "企业决策者内容推广", activity: "园区线下产品体验日", partner: "科技观察局", status: "Opportunity", potentialValue: 430000, owner: "周岚", createdAt: "2026-09-10" },
  { id: 8, name: "Noah Smith", company: "Cloudline AU", email: "noah@example.com", phone: "+61 2 8123 6670", source: "Partner", campaign: "客户成功案例推广", activity: "客户案例圆桌交流", partner: "BrightPath Consulting", status: "Lost", potentialValue: 120000, owner: "杨帆", createdAt: "2026-07-23" },
  { id: 9, name: "王楚", company: "启明医疗", email: "chu.wang@example.com", phone: "+86 135 6000 9921", source: "Campaign", campaign: "2026 Q4 品牌声量计划", activity: "未关联", partner: "未关联", status: "Contacted", potentialValue: 260000, owner: "林悦", createdAt: "2026-08-31" },
  { id: 10, name: "Aisha Lim", company: "Nexa Commerce", email: "aisha.lim@example.com", phone: "+60 3 2244 7801", source: "Webinar", campaign: "行业解决方案 Webinar", activity: "企业增长战略 Webinar", partner: "商业增长周刊", status: "New", potentialValue: 98000, owner: "赵欣", createdAt: "2026-09-01" },
  { id: 11, name: "郑宇", company: "万川物流", email: "yu.zheng@example.com", phone: "+86 138 7200 4432", source: "Other", campaign: "年度客户体验巡展", activity: "华南客户体验 Roadshow", partner: "未来制造社群", status: "Qualified", potentialValue: 310000, owner: "韩雪", createdAt: "2026-08-30" },
  { id: 12, name: "Daniel Koh", company: "Orbit Analytics", email: "daniel.koh@example.com", phone: "+65 6234 9081", source: "Organic", campaign: "未关联", activity: "未关联", partner: "未关联", status: "New", potentialValue: 145000, owner: "林悦", createdAt: "2026-09-02" },
];
